[package]
name = "foo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.41" # from crates.io
rand = { git = "https://github.com/rust-lang-nursery/rand" } # from online repo
bar = { path = "../bar" } # from a path in the local filesystem